# These are supported funding model platforms

github: GeauxWeisbeck4
patreon: GeauxWeisbeck4dev
open_collective: GeauxWeisbeck4
ko_fi: geauxweisbeck4
liberapay: GeauxWeisbeck4
issuehunt: GeauxWeisbeck4
otechie: GeauxWeisbeck4

